import initListeners from './listeners.js'
import initSampleDemo from './sample-demo.js'
import {
  getRequestedEditorVersion,
  loadEditorModule
} from './editor-module-loader.js'

/** Return explicit options supplied by the developer-playground test fixture. */
function getDemoInitOptions() {
  /** @type {Window & { __EDITOR_DEMO_INIT_OPTIONS?: Record<string, unknown> }} */
  const demoWindow = window
  return demoWindow.__EDITOR_DEMO_INIT_OPTIONS ?? {}
}

document.addEventListener('DOMContentLoaded', async() => {
  const playground = new URLSearchParams(window.location.search).get('mode') === 'playground'
  const sample = document.getElementById('sample-demo')
  const advanced = document.getElementById('playground-demo')
  const modeLink = document.getElementById('demo-mode-link')
  if (!sample || !advanced || !(modeLink instanceof HTMLAnchorElement)) return
  sample.hidden = playground
  advanced.hidden = !playground
  document.body.classList.toggle('sample-mode', !playground)
  if (playground) {
    modeLink.textContent = 'Try the sample'
    modeLink.href = './'
  } else {
    const editor = document.getElementById('editor')
    if (editor) document.getElementById('sample-editor-host')?.appendChild(editor)
  }
  try {
    const { default: initEditor } = await loadEditorModule()
    console.info('[image-editor demo] editor version:', getRequestedEditorVersion() || 'local')
    if (!playground) {
      initSampleDemo(initEditor)
      return
    }
    const editorInstance = await initEditor('editor', {
      montageAreaWidth: 512,
      montageAreaHeight: 512,
      editorContainerWidth: '100%',
      editorContainerHeight: 'calc(100vh - 9rem)',
      ...getDemoInitOptions()
    })
    initListeners(editorInstance)
  } catch (error) {
    console.error('[image-editor demo] Initialization failed:', error)
    const status = document.getElementById('sample-status')
    if (status) {
      status.textContent = 'The editor could not load. Reload the page to try again.'
      status.dataset.error = 'true'
    }
    if (playground) advanced.textContent = 'The editor could not load. Reload the page to try again.'
    document.getElementById('sample-reset')?.addEventListener('click', () => window.location.reload())
  }
})

/** Show the identity generated by the docs build; development has no metadata file. */
async function showBuildInfo() {
  const element = document.getElementById('demo-build-info')
  if (!element) return
  try {
    const response = await fetch(new URL('./build-info.json', document.baseURI))
    if (!response.ok || !response.headers.get('content-type')?.includes('json')) return
    const info = await response.json()
    if (typeof info.version !== 'string' || typeof info.sha !== 'string' || !/^[a-f0-9]{40}$/.test(info.sha)) return
    const link = document.createElement('a')
    link.href = `https://github.com/Anu3ev/image-editor/commit/${info.sha}`
    link.textContent = `v${info.version} · ${info.sha.slice(0, 7)}`
    link.title = typeof info.buildId === 'string' ? `Build ${info.buildId}` : 'View this commit'
    element.replaceChildren(link)
  } catch {
    // A missing development-only file must never block the sample.
  }
}
showBuildInfo()
