name: Deploy Demo to GitHub Pages

# Триггерим на пуш в мастер (или на правки только в папке demo)
on:
  push:
    branches:
      - master
    paths:
      - 'demo/**'
      - 'package.json'    # если скрипт build:docs в нём
      - 'vite.config.docs.js'

permissions:
  pages: write         # чтобы workflow мог пушить в Pages
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build demo for Pages
        run: npm run build:docs
          # предполагает, что в package.json есть скрипт "build:docs"
          # собирающий всё в папку docs/

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        # автоматически возьмёт ранее созданный артефакт и опубликует его
