name: Publish to npm on version bump

on:
  push:
    branches:
      - master
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0      # подтягиваем весь history, чтобы origin/master был доступен

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps
        run: npm ci

      - name: Check version bump and publish
        run: |
          # если package.json не менялся в последнем коммите — выходим
          git diff --quiet HEAD^ HEAD -- package.json && {
            echo "package.json не менялся — пропускаем"
            exit 0
          }

          # если в изменениях есть bump version — публикуем
          if git diff HEAD^ HEAD -- package.json | grep -q '"version":'; then
            echo "Обнаружен bump версии — публикуем"
            npm publish
          else
            echo "package.json менялся, но версия не тронута — пропускаем"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
